apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reactdemo
  name: reactdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reactdemo
    spec:
      containers:
      - image: rlarlgkd/fm3front:1
        name: reactdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 1010
    targetPort: 3000
  selector:
    app: reactdemo